
import 'package:get/get.dart';

class MyLocal implements Translations{
  @override
  Map<String, Map<String, String>> get keys =>{
    "ar" : {
      "splash_connect" : "...جاري الاتصال",
      "splash_alert_title" : "فشل الاتصال",
      "splash_alert_message" : "تأكد من ان جهازك متصل بالانترنت",
      "splash_alert_ok" : "حسنا",

      "choose_lang" : "اختر اللغه",

      "login_invalid" : "البريد الالكتروني او كلمه المرور خطاء",
      "login_invalid_btn" : "حسنا",
      "login_success" : "تم تسجيل الدخول بنجاح",
      "login_username" : "الاسم بالكامل",
      "login_password" : "كلمه المرور",
      "email" : "البريد الالكتروني",
      "phone" : "مثال : 5xxxxxx",
      "login_error" : "هذا الحقل مطلوب",
      "login_btn" : "تسجيل دخول",
      "login_first" : "يجب عليك تسجيل الدخول اولا",
      "or" : "او",
      "have_no_account" : "ليس لديك حساب ؟",
      "have_account" : "لديك حساب ؟",
      "register_btn" : "انشاء حساب",
      "save_successfully" : "تم الحفظ بنجاح",
      "password_incorrect" : "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
      "logout" : "تسجيل خروج",
      "myphone" : "رقم الهاتف",
      "edit_successfully" : "تم التعديل بنجاح",
      "logout_successfully" : "تم تسجيل الخروج بنجاح",

      "city_title" : "الاماره",
      "make_title" : "النوع",
      "make_search" : "ابحث هنا",
      "model_title" : "الطراز",

      "home_page1_title" : "الرئيسيه",
      "home_page2_title" : "اضافه سياره",
      "home_page3_title" : "الاعدادات",
      "home_welcome" : "مرحبا بك",
      "home_all" : "الكل",
      "home_sort_price_maxtomin" : "السعر من الاعلي الي الاقل",
      "home_sort_price_mintomax" : "السعر من الاقل الي الاعلي",
      "home_sort_kilo_maxtomin" : "الكيلوميتير من الاعلي الي الاقل",
      "home_sort_kilo_mintomax" : "الكيلوميتير من الاقل الي الاعلي",
      "home_sort_year_maxtomin" : "السنه من الاعلي الي الاقل",
      "home_sort_year_mintomax" : "السنه من الاقل الي الاعلي",
      "home_no_result" : "لايوجد نتائج للبحث",
      "home_favorite_empty" : "المفضله خاليه",
      "home_kilo" : "كيلو مترات",
      "home_year" : "السنه",

      "menu_setting" : "الاعدادات",
      "menu_change_lang" : "تغيير اللغه",
      "menu_location" : "موقعنا",
      "menu_exit" : "الخروج من التطبيق",
      "menu_alert_message" : "هل تود الخروج من التطبيق",
      "menu_alert_btn_cancel" : "الغاء",
      "menu_alert_btn_ok" : "موافق",

      "details_details" : "التفاصيل",
      "details_call" : "اتصل",
      "details_trim" : "الفئه",
      "details_year" : "السنه",
      "details_kilo" : "كيلومترات",
      "details_regional" : "المواصفات الاقليميه",
      "details_exterior" : "اللون الخارجي",
      "details_doors" : "عدد الابواب",
      "details_body_cond" : "الحاله",
      "details_mecha_cond" : "الحاله الميكانيكيه",
      "details_interior" : "اللون الداخلي",
      "details_horse" : "قوه الحصان",
      "details_body_type" : "نوع الجسم",
      "details_no_of" : "عدد الاسطوانات",
      "details_trans" : "نوع النقل",
      "details_fuel_type" : "نوع الوقود",
      "details_extras" : "اضافي",
      "details_steering" : "جهه القياده",
      "details_no" : "لايوجد",
      "details_posted" : "نشر في",

      "search_title" : "بحث",
      "search_city" : "اختر الاماره",
      "search_make" : "اختر النوع",
      "search_model" : "اختر الطراز",
      "search_trim" : "اختر الفئه",
      "search_regional" : "اختر المواصفات الاقليميه",
      "search_price" : "السعر (بالدرهم)",
      "search_year" : "السنه",
      "search_kilo" : "كيلومترات",
      "search_min" : "من",
      "search_max" : "الي",
      "search_result" : "نتيجه البحث",

      "mycars" : "سياراتي",
      "add_car" : "اضافه سياره",
      "next" : "التالي",
      "save" : "حفظ",
      "edit_car" : "تعديل السياره",
      "edit" : "تعديل",
      "choose_image" : "اختر صوره",
      "sure_delete" : "هل انت متأكد من انك تريد الحذف ؟",
      "no" : "لا",
      "yes" : "نعم",
      "price" : "السعر",
      "please_choose_all" : "الرجاء اختيار جميع الخيارات",

      "city_arabic" : "اختر الاماره بالعربيه",
      "city_english" : "اختر الاماره بالانجليزيه",
      "choose_regional_specs_arabic" : "اختر المواصفات الاقليميه بالعربيه",
      "choose_regional_specs_english" : "اختر المواصفات الاقليميه بالانجليزيه",
      "fuel_type_arabic" : "اختر نوع الوقود بالعربيه",
      "fuel_type_english" : "اختر نوع الوقود بالانجليزيه",
      "body_cond_arabice" : "اختر الحاله بالعربيه",
      "body_cond_english" : "اختر الحاله بالانجليزيه",
      "mecha_cond_arabic" : "اختر الحاله الميكانيكيه بالعربيه",
      "mecha_cond_english" : "اختر الحاله الميكانيكيه بالانجليزيه",

      "exterior_arabic" : "اختر اللون الخارجي بالعربيه",
      "exterior_english" : "اختر اللون الخارجي بالانجليزيه",
      "interior_arabic" : "اختر اللون الداخلي بالعربيه",
      "interior_english" : "اختر اللون الداخلي بالانجليزيه",
      "doors_arabice" : "اختر عدد الابواب بالعربيه",
      "doors_english" : "اختر عدد الابواب بالانجليزيه",
      "no_of_arabic" : "اختر عدد الاسطوانات بالعربيه",
      "no_of_english" : "اختر عدد الاسطوانات بالانجليزيه",

      "trans_arabic" : "اختر نوع النقل بالعربيه",
      "trans_english" : "اختر نوع النقل بالانجليزيه",
      "body_type_arabic" : "اختر نوع الجسم بالعربيه",
      "body_type_english" : "اختر نوع الجسم بالانجليزيه",
      "horse_arabice" : "اختر قوه الحصان بالعربيه",
      "horse_english" : "اختر قوه الحصان بالانجليزيه",
      "steering_arabic" : "اختر جهه القياده بالعربيه",
      "steering_english" : "اختر جهه القياده بالانجليزيه",
      "addition_arabic" : "ادخل الاضافات بالعربيه (اختياري)",
      "addition_english" : "ادخل الاضافات بالانجليزيه (اختياري)",
    },
    "en" : {
      "splash_connect" : "Connecting...",
      "splash_alert_title" : "Connection Faield",
      "splash_alert_message" : "Make sure your online",
      "splash_alert_ok" : "OK",

      "choose_lang" : "Choose Language",

      "login_invalid" : "Invalid Email or Password",
      "login_invalid_btn" : "ok",
      "login_success" : "Login Successfully",
      "login_username" : "Full Name",
      "email" : "Email",
      "login_password" : "Password",
      "phone" : "Exam : 5xxxxxxx",
      "login_error" : "This field requierd",
      "login_btn" : "Login",
      "login_first" : "You have to login first",
      "or" : "Or",
      "have_no_account" : "Have No Account ?",
      "have_account" : "Have an account ?",
      "register_btn" : "Register",
      "save_successfully" : "Save Successfully",
      "password_incorrect" : "The password must be at least 6 characters long",
      "logout" : "Log Out",
      "myphone" : "Phone Number",
      "edit_successfully" : "Edit Successfully",
      "logout_successfully" : "Logout Successfully",

      "city_title" : "City",
      "make_title" : "Make",
      "make_search" : "Search here",
      "model_title" : "Model",

      "home_page1_title" : "Home",
      "home_page2_title" : "Add Car",
      "home_page3_title" : "Settings",
      "home_welcome" : "Welcome",
      "home_all" : "All",
      "home_sort_price_maxtomin" : "Price Highest to Lowest",
      "home_sort_price_mintomax" : "Price Lowest to Highest",
      "home_sort_kilo_maxtomin" : "Kilo Highest to Lowest",
      "home_sort_kilo_mintomax" : "Kilo Lowest to Highest",
      "home_sort_year_maxtomin" : "Year Highest to Lowest",
      "home_sort_year_mintomax" : "Year Lowest to Highest",
      "home_no_result" : "Oops! No results",
      "home_favorite_empty" : "Favorite is empty",
      "home_kilo" : "Kms",
      "home_year" : "Year",

      "menu_setting" : "Settings",
      "menu_change_lang" : "Change Language",
      "menu_location" : "Location",
      "menu_exit" : "Exit",
      "menu_alert_message" : "You sure you want exit",
      "menu_alert_btn_cancel" : "Cancel",
      "menu_alert_btn_ok" : "Ok",

      "details_details" : "Details",
      "details_call" : "Call",
      "details_trim" : "Trim",
      "details_year" : "Year",
      "details_kilo" : "Kilometers",
      "details_regional" : "Regional Specs",
      "details_exterior" : "Exterior Color",
      "details_doors" : "Doors",
      "details_body_cond" : "Body Condition",
      "details_mecha_cond" : "Mechanical Condition",
      "details_interior" : "Interior Color",
      "details_horse" : "Horse Power",
      "details_body_type" : "Body Type",
      "details_no_of" : "No.of Cylinders",
      "details_trans" : "Transmission Type",
      "details_fuel_type" : "Fuel Type",
      "details_extras" : "Extras",
      "details_steering" : "Steering Side",
      "details_no" : "No Extras",
      "details_posted" : "Posted On",

      "search_title" : "Search",
      "search_city" : "Choose City",
      "search_make" : "Choose Make",
      "search_model" : "Choose Model",
      "search_trim" : "Choose Trim",
      "search_regional" : "Choose Regional Specs",
      "search_price" : "Price (AED)",
      "search_year" : "Year",
      "search_kilo" : "Kilometers",
      "search_min" : "Min",
      "search_max" : "Max",
      "search_result" : "Search Result",

      "mycars" : "My Cars",
      "add_car" : "Add Car",
      "next" : "Next",
      "save" : "Save",
      "edit_car" : "Edit Car",
      "edit" : "Edit",
      "choose_image" : "Choose Image",
      "sure_delete" : "Are you sure you want to delete ?",
      "no" : "No",
      "yes" : "Yes",
      "price" : "Price",
      "please_choose_all" : "Please select all options",

      "city_arabic" : "Choose City in Arabic",
      "city_english" : "Choose City in English",
      "choose_regional_specs_arabic" : "Choose regional specifications in Arabic",
      "choose_regional_specs_english" : "Choose regional specifications in English",
      "fuel_type_arabic" : "Choose the type of fuel in Arabic",
      "fuel_type_english" : "Choose the type of fuel in English",
      "body_cond_arabice" : "Choose the status in Arabic",
      "body_cond_english" : "Choose the status in English",
      "mecha_cond_arabic" : "Select the mechanical condition in Arabic",
      "mecha_cond_english" : "Choose the mechanical condition in English",

      "exterior_arabic" : "Choose the exterior color in Arabic",
      "exterior_english" : "Choose the exterior color in English",
      "interior_arabic" : "Choose the interior color in Arabic",
      "interior_english" : "Choose the interior color in English",
      "doors_arabice" : "Choose the number of doors in Arabic",
      "doors_english" : "Choose the number of chapters in English",
      "no_of_arabic" : "Choose the number of cylinders in Arabic",
      "no_of_english" : "Choose the number of cylinders in English",

      "trans_arabic" : "Choose the type of transportation in Arabic",
      "trans_english" : "Choose the type of transfer in English",
      "body_type_arabic" : "Choose your body type in Arabic",
      "body_type_english" : "Choose your body type in English",
      "horse_arabice" : "Choose horse power in Arabic",
      "horse_english" : "Choose horse power in English",
      "steering_arabic" : "Choose the driving direction in Arabic",
      "steering_english" : "Choose the driving force in English",
      "addition_arabic" : "Enter the additions in Arabic (optional)",
      "addition_english" : "Enter additions in English (optional)",
    }
  };

}